global:
  scrape_interval: 15s
  evaluation_interval: 30s
  external_labels:
    monitor: 'main-monitor'
alerting:
  alertmanagers:
    - static_configs:
      - targets: ["alertmanager:9093"]
rule_files:
  - "/etc/prometheus/rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  

###################################################
#           Kube State Metrics Arvsn              #
# #################################################
  - job_name: kube-state-metrics-arvan
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ['ksm.arvan.ir']
        labels:
          zone: "arvancluster"

###################################################
#           Flask App Metrics                     #
# #################################################
  - job_name: flask-app-metrics
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ['locip.arvan.ir']